// <auto-generated />
using System;
using FinFlow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinFlow.Infrastructure.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260420170011_AddTenantUsageSnapshots")]
partial class AddTenantUsageSnapshots
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FinFlow.Domain.Entities.TenantUsageSnapshot", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<int>("ChatbotMessagesUsed")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("chatbot_messages_used");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true)
                    .HasColumnName("is_active");

                b.Property<Guid>("IdTenant")
                    .HasColumnType("uuid")
                    .HasColumnName("id_tenant");

                b.Property<DateOnly>("PeriodEnd")
                    .HasColumnType("date")
                    .HasColumnName("period_end");

                b.Property<DateOnly>("PeriodStart")
                    .HasColumnType("date")
                    .HasColumnName("period_start");

                b.Property<int>("OcrPagesUsed")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("ocr_pages_used");

                b.Property<long>("StorageUsedBytes")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasDefaultValue(0L)
                    .HasColumnName("storage_used_bytes");

                b.HasKey("Id");

                b.HasIndex("IdTenant", "PeriodStart", "PeriodEnd")
                    .IsUnique()
                    .HasDatabaseName("ux_tenant_usage_snapshot_period");

                b.ToTable("tenant_usage_snapshot", (string)null);
            });

        modelBuilder.Entity("FinFlow.Domain.Entities.TenantUsageSnapshot", b =>
            {
                b.HasOne("FinFlow.Domain.Entities.Tenant", null)
                    .WithMany()
                    .HasForeignKey("IdTenant")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
